### ISSUE TITLE
Version 0.3.1 was released with an older version of the artifacts.

### ISSUE THREAD

**Issue by junhaoliao** [y-scope/clp-ffi-js#44]
### Bug

Version 0.3.1 released at https://www.npmjs.com/package/clp-ffi-js contained an older version of the artifacts because @junhaoliao made the release without rebuilding, though he did used the `npm run release` script which checked if there were any uncommitted changes.

Automation should be added to reduce manual errors in the future.

### clp-ffi-js version

32b1220ccfbe59b30037dfc85dd3ded500114798

### Environment

Ubuntu 20.04

### Reproduction steps

1. `npm install clp-ffi-js`.
2. Create a stream reader which reads an IRv2 file and perform `filterLogEvents`.
3. Observe error "Log level filtering is not yet supported in this reader." was logged although that should have been removed in 5f9e50de7f375bbac0525c4d58f65e1ac9b57859

**Comment by junhaoliao** [comment]
A newer version has been released at https://github.com/y-scope/clp-ffi-js/releases/tag/v0.3.3 / https://www.npmjs.com/package/clp-ffi-js/v/0.3.3

**Comment by junhaoliao** [comment]
@kirkrodrigues / @davemarco 

Any objection if we [`npm unpublish`](https://docs.npmjs.com/cli/v9/commands/npm-unpublish) 0.3.1 and 0.3.2 (see #48) on the npm registry?

**Comment by kirkrodrigues** [comment]
> @kirkrodrigues / @davemarco
> 
> Any objection if we [`npm unpublish`](https://docs.npmjs.com/cli/v9/commands/npm-unpublish) 0.3.1 and 0.3.2 (see #48) on the npm registry?

No, go for it.

**Comment by junhaoliao** [comment]
> > [@kirkrodrigues](https://github.com/kirkrodrigues) / [@davemarco](https://github.com/davemarco)
> > Any objection if we [`npm unpublish`](https://docs.npmjs.com/cli/v9/commands/npm-unpublish) 0.3.1 and 0.3.2 (see [#48](https://github.com/y-scope/clp-ffi-js/issues/48)) on the npm registry?
> 
> No, go for it.

done
